apiVersion: batch/v1
kind: Job
metadata:
  generateName: vegeta
  labels:
    app: vegeta
spec:
  parallelism: 10
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: vegeta
          image: peterevans/vegeta
          command: ["sh", "-c"]
          args: ['echo "GET http://nginx" | vegeta attack -rate=1000 -duration=120s -header "Content-Cache: no-cache" | vegeta report']
          resources:
            requests:
              cpu: 500m
              memory: 1.5Gi
