apiVersion: v1
kind: Pod
metadata:
  name: probe
  labels:
    app: probe
spec:
  containers:
    - name: probe
      image: YOUR_BUILD_IMAGE # Fixme
      readinessProbe:
        initialDelaySeconds: 10
        periodSeconds: 30
        failureThreshold: 2
        successThreshold: 1
        timeoutSeconds: 5
        httpGet:
          port: 80
          path: /
      livenessProbe:
        httpGet:
          port: 80
          path: /
---
apiVersion: v1
kind: Service
metadata:
  name: probe
spec:
  selector:
    app: probe
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
